create table if not exists public.manner_ratings (
  id bigint generated by default as identity primary key,
  rater_id uuid references auth.users(id) on delete cascade not null,
  rated_id uuid references auth.users(id) on delete cascade not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text check (char_length(comment) <= 500),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table public.manner_ratings enable row level security;

create policy "Users can create their own ratings"
  on public.manner_ratings for insert
  with check (auth.uid() = rater_id);

create policy "Users can view ratings they created or received"
  on public.manner_ratings for select
  using (auth.uid() = rater_id or auth.uid() = rated_id);

-- Add index for performance
create index manner_ratings_rater_id_idx on public.manner_ratings(rater_id);
create index manner_ratings_rated_id_idx on public.manner_ratings(rated_id);
